version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - "/mnt/c/airflow/dags:/usr/local/airflow/dags"
      - "/mnt/c/airflow/logs:/usr/local/airflow/logs"
      - "/mnt/c/airflow/plugins:/usr/local/airflow/plugins"
      - "/mnt/c/airflow/data:/usr/local/airflow/data"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: webserver

  scheduler:
    image: puckel/docker-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - "/mnt/c/airflow/dags:/usr/local/airflow/dags"
      - "/mnt/c/airflow/logs:/usr/local/airflow/logs"
      - "/mnt/c/airflow/plugins:/usr/local/airflow/plugins"
      - "/mnt/c/airflow/data:/usr/local/airflow/data"
    depends_on:
      - postgres
    command: scheduler
